cookbook 'drupal', git: 'https://github.com/newmediadenver/drupal', branch: '2.x'
cookbook 'nmddatabase', git: 'https://github.com/arknoll/nmddatabase', branch: 'master'
cookbook 'apt', '~> 2.3.0'
cookbook 'apache2', '~> 1.8.14'
cookbook 'build-essential', '~> 1.4.2'
cookbook 'git', '~> 2.8.4'
cookbook 'dmg', '~> 2.0.8'
cookbook 'openssl', '~> 1.1.0'
cookbook 'php', '~> 1.2.6'
cookbook 'ssh_known_hosts', '~> 1.1.0'
cookbook 'sudo', '~> 2.5.2'
